//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGeStockWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        public int idF { get; set; }
        public string nomF { get; set; }
        public string telF { get; set; }
        public string codeF { get; set; }
    }
}
