//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGeStockWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneVente
    {
        public int idLV { get; set; }
        public int idV { get; set; }
        public decimal qte { get; set; }
        public decimal puV { get; set; }
        public int idApp { get; set; }
        public int idP { get; set; }
    }
}
