//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGeStockWebForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdStockMGL2021Entities : DbContext
    {
        public bdStockMGL2021Entities()
            : base("name=bdStockMGL2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approvisionnement> Approvisionnement { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<LigneVente> LigneVente { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Vente> Vente { get; set; }
    }
}
