//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGeStockWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int idP { get; set; }
        public string nomP { get; set; }
        public string descriptionP { get; set; }
        public decimal qteP { get; set; }
        public decimal qteSeuil { get; set; }
        public decimal pu { get; set; }
        public Nullable<int> idCat { get; set; }
    }
}
